### ISSUE TITLE
ImportError: No module named 'django'

### ISSUE THREAD

**Issue by bodrich** [philchristensen/antioch#6]
`root@ubuntu:~/antioch# docker-compose run webapp manage.py migrate
Starting antioch_memcached_1 ...
Starting antioch_postgres_1 ...
Starting antioch_memcached_1
Starting antioch_redis_1 ...
Starting antioch_postgres_1
Starting antioch_postgres_1 ... done
+ export PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
+ PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
+ cd /usr/src/app
+ '[' manage.py = '' ']'
+ '[' manage.py = manage.py ']'
+ exec python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    import django
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
`

**Comment by bodrich** [comment]
i change python3 on python3.7 and:
`root@ubuntu:~/antioch# docker-compose run webapp manage.py migrate
Starting antioch_memcached_1 ...
Starting antioch_postgres_1 ...
Starting antioch_memcached_1
Starting antioch_redis_1 ...
Starting antioch_postgres_1
Starting antioch_memcached_1 ... done
+ export PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
+ PATH=/bin:/usr/bin:/usr/sbin:/usr/local/bin
+ cd /usr/src/app
+ '[' manage.py = '' ']'
+ '[' manage.py = manage.py ']'
+ exec python3.7 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/usr/local/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/antioch/urls.py", line 19, in <module>
    url(r'', include('antioch.client.urls')),
  File "/usr/local/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/antioch/client/urls.py", line 9, in <module>
    from django.contrib.auth.views import login
ImportError: cannot import name 'login' from 'django.contrib.auth.views' (/usr/local/lib/python3.7/site-packages/django/contrib/auth/views.py)
`

**Comment by philchristensen** [comment]
Hey, sorry for my late response on this, but I'm sure this has something to do with either a new version of Django (last tested with 2.0.2) or using Python 3.7 (which should be fine itself, but might introduce new module behavior, etc).

I'm really trying to find some time to get back to this, but the last time I was working on it I made a lot of major changes re: django/python version support, and it's likely to be a bit flaky still.

Thanks for your interest, though. I hope you keep following along and can give a try the next time I can get a round of updates out. I'll try to get it pinned to specific versions so it doesn't drift before someone gets to play with it.

**Comment by philchristensen** [comment]
Hmm, actually, I just took a quick pass at this and everything seemed to work fine out of the box. Just to be clear, you have the rest of the docker-compose project running in another terminal when you execute this, right?

**Comment by philchristensen** [comment]
FWIW, I am seeing strange behavior coming out in the tests, even though little or nothing has changed.

**Comment by bodrich** [comment]
> you have the rest of the docker-compose project running in another terminal when you execute this
yeap

**Comment by bodrich** [comment]
Don't work :(
Error:
`
ERROR: Service 'webapp' failed to build: The command '/bin/sh -c pipenv install --system --dev --deploy --ignore-pipfile' returned a non-zero code: 1
`
Full log ssh attached
[putty.log](https://github.com/philchristensen/antioch/files/2363805/putty.log)

**Comment by bodrich** [comment]
Hosting digitalocean.com, os Ubuntu 16.04 64 bit

**Comment by philchristensen** [comment]
Yeah, I'm in the midst of refactoring to use Pipfile. This all happened because of version drift that would have been prevented by using a lockfile. I'll update this thread when it's done.

**Comment by philchristensen** [comment]
Alright, I finished refactoring to use Pipfile to track library requirements, and have decided to just focus on support for latest stuff, so this is pinned on Python 3.7 and Django 2.1 for now.

I blew away my Docker installation, installed fresh, and ran the steps in the README, and everything worked, at least as far as getting in to the game and being able to run commands.

Note that once you're in, there's a *lot* of rough spots. The object editor is still undergoing major renovations, so although `edit here` or some other edit command will open the editor, it's not entirely useful. You can still look at stuff, dig new rooms, tunnel between them, create objects, etc. it's just the more interactive stuff that opens up UI boxes and so forth that probably won't work.

**Comment by philchristensen** [comment]
Out of the box it’s only configured to work on localhost.

You’ll need to update ALLOWED_HOSTS in development.py to have the host name/IP you’re using to connect. From here it’s just basic Django config.

https://docs.djangoproject.com/en/2.1/ref/settings/
